spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lab10
    username: postgres
    password: postgresql
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  profiles:
    active: "dev"
  application:
    name: "lab"

server:
  port: 8099
