spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/egor
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

server:
  port: 8099
